### ISSUE TITLE
v0.20 - Array Index Out of Bounds on Midboss Spells

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#6] opened 2015-07-07 14:04 UTC
As of a5c3cc79d087ec398f1b0155f290b171665ffcaf, playing Stage 2 via Stage practice crashes on mid boss Minoriko's second attack, which cites the following:

```
Array index out of bounds.
(配列のサイズを超えています)
Z:/Users/andrewfan/ssh/Ephemeral-Unnatural-Balance/System/Effect.dnh 
Effect.dnh line(行)=1588

↓
			
			let objtext3b = ObjText_Create;
```

**Comment by Sparen** [comment] 2015-07-07 14:05
Oh yeah, and remember for the future that paths are case sensitive if you decide to use archives.

**Comment by ExPorygon** [comment] 2015-07-08 22:02
Tell me if you were bombing or not during the spell, or if you were doing anything else unusual.

**Comment by Sparen** [comment] 2015-07-08 22:38
I have no idea. I will attempt to replicate the bug.

**Comment by Sparen** [comment] 2015-07-08 22:53
Confirmed:
Rin Satsuki, Normal Mode, no deaths or bombs during non spell. *I believe it defaults to Hard Mode
Kasen Ibaraki, Easy Mode, no deaths or bombs during non spell. *Defaults to Hard Mode

Due to the lack of any array indexing in Effect.dnh at line 1588, the problem is most likely elsewhere in the script that included the file.

Of course, I don't know enough about the library structures yet, but you're including the same file twice in the same script as well, and Danmakufu is not giving you a proper error for that. So I can't discern the real problem.

**Comment by Sparen** [comment] 2015-07-11 15:11
Confirmed on Stage 3, Spell Practice, Easy Mode, Rin Satsuki

Player was already dead when the error occurred at the start of Aya's mid boss second attack.

**Comment by Sparen** [comment] 2015-07-13 13:22
Update: This occurs when using Stage Practice from the package but did not occur when running Test Stage.dnh from the individual stage folders.

**Comment by ExPorygon** [comment] 2015-07-14 04:38
Update: This error occurs for any spellcard that occurs during stage practice on any stage.

    if(IsCommonDataAreaExists("PlayState")) {
				if(GetAreaCommonData("PlayState","Mode","")!="Practice") {
					ObjText_SetText(objtext3b,rtos("00",GetAreaCommonData("History","Stage History",[])[SpellID][1]));
				}
				else {
					ObjText_SetText(objtext3b,rtos("00",GetAreaCommonData("History","Spell History",[])[SpellID][1]));
				}
			}
```
This code section is the culprit, chiefly the retrieval of the area common data for the stage history. Will continue investigating why.

**Comment by ExPorygon** [comment] 2015-07-14 04:46
I've discovered the cause. The "Spell History" part of the "History" common data area does not exist. The correct common data are "Stage History" and "Practice History". I can only assume that it somehow still recognized the "Spell History" as valid and tried checking for values in a nonexistant array.

**Comment by ExPorygon** [comment] 2015-07-14 23:55
Fixed in 648c7e8e81238f58d2510b97c1449434011f2e8c.

**Closed by ExPorygon** 2015-07-14 23:55 UTC
Labels: bug
